### ISSUE TITLE
Configure-Link on Manage display form doesn't work

### ISSUE THREAD

**Issue by olafgrabienski** [backdrop-contrib/videojs#2]
I'm testing this module on a Backdrop (Tugboat) demo site, because I'm interested in the option to use a poster image for videos.

Adding a Video field and displaying it with the Video.js format works fine. But when I click the *Configure* link at  `admin/structure/types/manage/post/display/default`, the inline form doesn't open, so I'm not able to adjust the Player dimensions or to add a Poster image style.

Clicking the *Configure* link with JavaScript disabled results in a blanke page with the following message:

> Call to undefined function field_info_field_by_id()

Message in DBlog:

`Error: Call to undefined function field_info_field_by_id() in videojs_utility::findFieldsByType() (line 214 of /var/lib/tugboat/backdrop/modules/videojs/includes/videojs.utility.inc).`

**Comment by laryn** [comment]
@olafgrabienski Try changing `field_info_field_by_id` to `field_info_field`.

**Comment by olafgrabienski** [comment]
> Try changing `field_info_field_by_id` to `field_info_field`.

@laryn Thanks for the hint! Not sure where to do this. Do you suggest to change the module code and see if that helps?

I found the following line with `field_info_field_by_id`:

https://github.com/backdrop-contrib/videojs/blob/b0775d75ba9afb83536763c51cc8ba76bf52a4b7/includes/videojs.utility.inc#L214

**Comment by laryn** [comment]
@olafgrabienski Yes, try changing that line -- that's the line called out in the error message and I think that function no longer exists, but the default `field_info_field` uses the id as an argument in Backdrop.

**Comment by olafgrabienski** [comment]
Great, that works on my test site! After changing `field_info_field_by_id` to `field_info_field`, when I click the _Configure_ link at `admin/structure/types/manage/post/display/default`, the inline form _does_ open.

I hope this helps! (I don't plan to use the module for the time being, so I'm a bit hesitant to provide a PR.)

**Comment by laryn** [comment]
I've added a PR.

**Comment by laryn** [comment]
This is fixed in https://github.com/backdrop-contrib/videojs/commit/cc954eebac2d72037b19106eb5ec9528cb6902bf
