### ISSUE TITLE
Update default version of the VideoJS library

### ISSUE THREAD

**Issue by laryn** [backdrop-contrib/videojs#6]
Following up on https://github.com/backdrop-contrib/videojs/issues/4 I'm finding the "CC" icon isn't showing up right:

![CleanShot 2024-08-16 at 15 03 49@2x](https://github.com/user-attachments/assets/b76a2880-a5fb-40c1-a313-f42cef945492)

**Comment by laryn** [comment]
This seems to be coming out of the CSS file and library... I'm going to convert this issue to one that upgrades the version of the library.

**Comment by laryn** [comment]
@herbdool I've added a PR for this which also bundles the library. Bundling the library requires bumping license to GPL-3.0 since the library is released under Apache 2.0 [which is compatible with GPL-3.0](https://www.apache.org/licenses/GPL-compatibility.html). This is accounted for in the PR.

If you prefer not to bundle the library, we could also simply bump the version that is being pulled from the CDN. This is also happening in the PR.

The newer version of the library solves the initial problem I was seeing.

![CleanShot 2024-08-16 at 16 21 39@2x](https://github.com/user-attachments/assets/b0d273a5-c873-4a10-9aaa-9d4112a4be5d)

**Comment by herbdool** [comment]
Thanks @laryn. By the way, I haven't used this module on any site (and it shows since I hadn't updated it in years). I'd prefer to step down from being maintainer. Care to take over?
